services:
    marcosfpo.groupicon.view_listener:
        class: marcosfpo\groupicon\event\view_listener
        arguments:
            - @template
            - @dbal.conn
        tags:
            - { name: event.listener }

    marcosfpo.groupicon.acp_listener:
        class: marcosfpo\groupicon\event\acp_listener
        arguments:
            - @request
            - @template
            - @log
            - @user
            - @config
        tags:
            - { name: event.listener }